version: "3.5"

services:

 db:
  image: mysql:latest
  container_name: mysql-tic-tac-toe-app
  environment:
   MYSQL_ROOT_PASSWORD: root
   MYSQL_ROOT_HOST: '%'
  ports:
   - "3306:3306"
  volumes:
   - ./dbdata:/var/lib/mysql
   - ./TicTacToeSQL.sql:/docker-entrypoint-initdb.d/TicTacToeSQL.sql
  restart: always


 phpmyadmin:
  image: phpmyadmin/phpmyadmin:latest
  container_name: my-php-myadmin-tic-tac-toe-app
  ports:
   - "80:80"
  restart: always
  depends_on:
   - db
  environment:
   SPRING_DATASOURCE_USERNAME: root
   SPRING_DATASOURCE_PASSWORD: root

 tictactoeapp:
  image: tictactoe-app
  container_name: tictactoe-app-container
  build:
   context: game\
   dockerfile: Dockerfile
  ports:
   - "13378:13378"
  restart: always
  depends_on:
   - db
  environment:
   SPRING_DATASOURCE_URL: jdbc:mysql://mysql-tic-tac-toe-app:3306/tictactoe?useUnicode=true&characterEncoding=utf8
   SPRING_DATASOURCE_USERNAME: root
   SPRING_DATASOURCE_PASSWORD: root