-- MySQL Script generated by MySQL Workbench
-- Sat Nov  6 18:17:58 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema tictactoe
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema tictactoe
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tictactoe` DEFAULT CHARACTER SET utf8 ;
USE `tictactoe` ;

-- -----------------------------------------------------
-- Table `tictactoe`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tictactoe`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `mail` VARCHAR(255) NULL,
  `password` VARCHAR(255) NULL,
  `username` VARCHAR(50) NULL,
  `activated` BIT(1) NULL,
  `rank_score_3x3` INT NULL,
  `games_won_3x3_rank` INT NULL,
  `games_won_3x3_no_rank` INT NULL,
  `rank_score_15x15` INT NULL,
  `games_won_15x15_rank` INT NULL,
  `games_won_15x15_no_rank` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tictactoe`.`user_role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tictactoe`.`user_role` (
  `id` INT NOT NULL,
  `user_role_name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tictactoe`.`user_has_user_role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tictactoe`.`user_has_user_role` (
  `user_id` INT NOT NULL,
  `user_role_id` INT NOT NULL,
  PRIMARY KEY (`user_id`, `user_role_id`),
  INDEX `fk_user_has_user_role_user_role1_idx` (`user_role_id` ASC) VISIBLE,
  INDEX `fk_user_has_user_role_user_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_has_user_role_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `tictactoe`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_user_role_user_role1`
    FOREIGN KEY (`user_role_id`)
    REFERENCES `tictactoe`.`user_role` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tictactoe`.`chat_message`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tictactoe`.`chat_message` (
  `id` INT NOT NULL,
  `content` TEXT(1000) NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_chat_message_user1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_chat_message_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `tictactoe`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tictactoe`.`session`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tictactoe`.`session` (
  `id` INT NOT NULL,
  `session_game_type` VARCHAR(45) NULL,
  `game_winner_id` INT NULL,
  `circle_side_player_id` INT NOT NULL,
  `cross_side_player_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_session_user1_idx` (`game_winner_id` ASC) VISIBLE,
  INDEX `fk_session_user2_idx` (`circle_side_player_id` ASC) VISIBLE,
  INDEX `fk_session_user3_idx` (`cross_side_player_id` ASC) VISIBLE,
  CONSTRAINT `fk_session_user1`
    FOREIGN KEY (`game_winner_id`)
    REFERENCES `tictactoe`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_session_user2`
    FOREIGN KEY (`circle_side_player_id`)
    REFERENCES `tictactoe`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_session_user3`
    FOREIGN KEY (`cross_side_player_id`)
    REFERENCES `tictactoe`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

use tictactoe;
insert into user_role values(1, "ROLE_USER");
insert into user values(0, "-", "-", "-", 1, 0, 0, 0, 0, 0, 0);
